name: Generate

on:
  schedule:
    - cron: "0 0 * * *" # Daily run.
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # checkout
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: ./generate.sh

      # - name: Check changes
      #   uses: dorny/paths-filter@v2
      #   id: changes
      #   with:
      #     base: main
      #     filters: |
      #       pkg:
      #         - 'pkg/**'

      # TODO: get information about tools version and add to pr commit message.

      - name: Create PR
        # if: steps.changes.outputs.pkg == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: Pull latest updates from github.com/golang/tools
          commit-message: Pull latest updates from github.com/golang/tools
          branch: pull-tools-updates
          delete-branch: true
